# Generated by Django 6.0.7 on 2026-08-05 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('stability_days', models.FloatField(default=1.0, verbose_name='Eslab qolish kuchi')),
                ('next_review_date', models.DateField(default=django.utils.timezone.now, verbose_name='Keyingi takrorlash sanasi')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to='catalog.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Joriy ketma-ketlik')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Eng uzun ketma-ketlik')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Oxirgi faollik sanasi')),
                ('freezes_available', models.PositiveIntegerField(default=1, verbose_name="Mavjud 'muz'lar soni")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('amount', models.IntegerField(verbose_name='XP miqdori')),
                ('source', models.CharField(choices=[('test', 'Test yakunlandi'), ('streak', 'Streak'), ('review', 'Takrorlash'), ('bonus', 'Bonus')], max_length=10, verbose_name='Manba')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
