# Generated by Django 6.0.7 on 2026-09-07 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_grade_question_lifecycle'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (EN)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Tavsif (UZ)')),
                ('description_ru', models.CharField(blank=True, max_length=255, verbose_name='Tavsif (RU)')),
                ('description_en', models.CharField(blank=True, max_length=255, verbose_name='Tavsif (EN)')),
                ('icon', models.CharField(blank=True, help_text='Emoji yoki ikonka kodi', max_length=32, verbose_name='Ikonka')),
                ('metric', models.CharField(choices=[('questions', 'Javob berilgan savollar'), ('correct', "To'g'ri javoblar"), ('tests', 'Yakunlangan testlar'), ('streak', 'Ketma-ket kunlar'), ('xp', 'Umumiy XP'), ('subject_stars', 'Fan darajasi (⭐ x10)'), ('perfect', 'Xatosiz testlar')], max_length=20, verbose_name="O'lchov")),
                ('threshold', models.PositiveIntegerField(verbose_name='Chegara qiymati')),
                ('xp_reward', models.PositiveIntegerField(default=0, verbose_name='XP mukofoti')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Yutuq',
                'verbose_name_plural': 'Yutuqlar',
                'ordering': ['metric', 'threshold', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('value_at_unlock', models.PositiveIntegerField(default=0, verbose_name='Qiymat')),
            ],
            options={
                'verbose_name': "Foydalanuvchi yutug'i",
                'verbose_name_plural': 'Foydalanuvchi yutuqlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='reviewcard',
            options={'ordering': ['next_review_date', 'id']},
        ),
        migrations.AddField(
            model_name='reviewcard',
            name='ease_factor',
            field=models.FloatField(default=2.5, verbose_name='Yengillik koeffitsiyenti'),
        ),
        migrations.AddField(
            model_name='reviewcard',
            name='interval_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Interval (kun)'),
        ),
        migrations.AddField(
            model_name='reviewcard',
            name='lapses',
            field=models.PositiveIntegerField(default=0, verbose_name='Unutishlar soni'),
        ),
        migrations.AddField(
            model_name='reviewcard',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi takrorlash'),
        ),
        migrations.AddField(
            model_name='reviewcard',
            name='repetitions',
            field=models.PositiveIntegerField(default=0, verbose_name="Ketma-ket to'g'ri javoblar"),
        ),
        migrations.AddIndex(
            model_name='reviewcard',
            index=models.Index(fields=['user', 'next_review_date'], name='progress_re_user_id_150047_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewcard',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='uniq_review_card_per_question'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='progress.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', '-created_at'], name='progress_us_user_id_811b35_idx'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='uniq_user_achievement'),
        ),
    ]
