# Generated by Django 6.0.7 on 2026-08-22 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Ruscha'), ('en', 'Inglizcha')], default='uz', max_length=5, verbose_name='Interfeys tili'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram username'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('device_id', models.CharField(max_length=128, verbose_name='Qurilma identifikatori')),
                ('platform', models.CharField(choices=[('ios', 'iOS (iPhone / iPad)'), ('android', 'Android'), ('web', 'Brauzer'), ('desktop', 'Desktop'), ('other', 'Boshqa')], default='other', max_length=10, verbose_name='Platforma')),
                ('push_token', models.CharField(blank=True, max_length=512, verbose_name='Push token')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='OS versiyasi')),
                ('app_version', models.CharField(blank=True, max_length=50, verbose_name='Ilova versiyasi')),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Ruscha'), ('en', 'Inglizcha')], default='uz', max_length=5, verbose_name='Til')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qurilma',
                'verbose_name_plural': 'Qurilmalar',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='account_dev_user_id_8da8e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='uniq_user_device')],
            },
        ),
    ]
