# Generated by Django 6.0.7 on 2026-08-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_plan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('manual', "Qo'lda (Telegram orqali)")], max_length=10, verbose_name='Provayder'),
        ),
    ]
