# Generated by Django 6.0.7 on 2026-08-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_payment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('expired', "Muddati o'tgan"), ('cancelled', 'Bekor qilingan')], default='active', max_length=15, verbose_name='Holati'),
        ),
    ]
