# Generated by Django 6.0.7 on 2026-08-22 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_payment_plan(apps, schema_editor):
    """Eski arizalarda tarif faqat obuna orqali bog'langan edi. Endi ariza
    o'zida ham tarifni saqlaydi — obuna o'chsa ham qaysi tarif so'ralgani
    ma'lum bo'lib qoladi."""
    Payment = apps.get_model('billing', 'Payment')
    # `update(plan=F('subscription__plan'))` ishlamaydi — Django `update()` da
    # JOIN orqali maydonga murojaat qilishga ruxsat bermaydi.
    batch = []
    rows = Payment.objects.filter(
        plan__isnull=True, subscription__isnull=False
    ).values_list('id', 'subscription__plan_id')
    for payment_id, plan_id in rows.iterator(chunk_size=1000):
        if plan_id:
            batch.append(Payment(id=payment_id, plan_id=plan_id))

    if batch:
        Payment.objects.bulk_update(batch, ['plan'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_subscription_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Aloqa telefoni'),
        ),
        migrations.AddField(
            model_name='payment',
            name='contact_telegram',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram username'),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, verbose_name='Foydalanuvchi izohi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqti"),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqqan admin"),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (EN)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Rad etilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=15, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi (UZ)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('expired', "Muddati o'tgan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=15, verbose_name='Holati'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='billing_pay_user_id_562e66_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='billing_pay_status_bc3ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='billing_sub_user_id_211f85_idx'),
        ),
        migrations.RunPython(backfill_payment_plan, migrations.RunPython.noop),
    ]
