# Generated by Django 6.0.7 on 2026-09-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_payment_options_alter_plan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='can_view_explanations',
            field=models.BooleanField(default=False, verbose_name="Yechim izohlarini ko'radi"),
        ),
        migrations.AddField(
            model_name='plan',
            name='code',
            field=models.SlugField(blank=True, help_text='Kodda murojaat qilish uchun barqaror kalit: free, pro_basic, pro_full.', max_length=32, verbose_name='Tizim kodi'),
        ),
        migrations.AddField(
            model_name='plan',
            name='daily_topic_limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Bir kunda nechta TURLI mavzuda test ishlash mumkin. Bo'sh qoldirilsa — cheklovsiz.", null=True, verbose_name='Kunlik mavzu limiti'),
        ),
        migrations.AddField(
            model_name='plan',
            name='explanation_limit_per_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Kuniga nechta testning izohini ochish mumkin. Bo'sh qoldirilsa — cheklovsiz.", null=True, verbose_name='Kunlik izoh limiti'),
        ),
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Kelajakdagi flaglar uchun erkin JSON. Masalan: {"ai_tutor": true, "mock_exam": false}', verbose_name="Qo'shimcha imkoniyatlar"),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_pro',
            field=models.BooleanField(default=False, help_text="Pro tariflarda kunlik mavzu limiti qo'llanilmaydi.", verbose_name='Pro tarif'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_question_count',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Bir testdagi maksimal savol'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('code',), name='uniq_plan_code'),
        ),
    ]
