# Generated by Django 6.0.7 on 2026-09-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_plan_can_view_explanations_plan_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='can_choose_question_count',
            field=models.BooleanField(default=True, help_text="O'chirilsa test har doim eng kichik to'plam bilan boshlanadi.", verbose_name="Savol sonini o'zi tanlaydi"),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_use_exam_mode',
            field=models.BooleanField(default=True, help_text="O'chirilsa faqat «O'rganish» rejimi ochiq bo'ladi.", verbose_name='Imtihon rejimi (vaqt chegarasi bilan)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_view_analytics',
            field=models.BooleanField(default=True, help_text="O'chirilsa faqat umumiy ball va daraja ko'rinadi.", verbose_name='Zaif mavzular va batafsil tahlil'),
        ),
        migrations.AddField(
            model_name='plan',
            name='history_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Necha kunlik natija ko'rinadi. Bo'sh qoldirilsa — butun tarix.", null=True, verbose_name='Natijalar tarixi (kun)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='mistake_test_daily_limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Bo'sh — cheksiz, 0 — faqat xatolar ro'yxatini ko'radi.", null=True, verbose_name='Xatolardan test tuzish (kuniga)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='review_cards_daily_limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Bo'sh — cheksiz, 0 — takrorlash yopiq.", null=True, verbose_name='Takrorlash kartalari (kuniga)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='streak_freezes_per_month',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text="Bo'sh — cheksiz, 0 — muzlatish yo'q.", null=True, verbose_name='Streak muzlatish (oyiga)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Faqat belgi: tarif pullik ekanini bildiradi. Cheklovlar quyidagi maydonlardan olinadi, bu ptichkadan emas.', verbose_name='Pullik tarif'),
        ),
    ]
