# Generated by Django 6.0.7 on 2026-09-21 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('feature', models.CharField(choices=[('mistake_test', 'Xatolardan test tuzish'), ('review_card', 'Takrorlash kartasi'), ('streak_freeze', 'Streak muzlatish')], max_length=32, verbose_name='Imkoniyat')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana (UZT)')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Nechta marta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_feature_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunlik foydalanish',
                'verbose_name_plural': 'Kunlik foydalanishlar',
                'ordering': ['-date', 'feature'],
                'indexes': [models.Index(fields=['user', 'feature', 'date'], name='common_dail_user_id_6d9ed4_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'feature', 'date'), name='uniq_daily_feature_usage')],
            },
        ),
    ]
