# Generated by Django 5.2.17 on 2026-09-24 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfeatureusage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('type', models.CharField(choices=[('feedback', 'Fikr / Taklif'), ('bug', 'Muammo / Xatolik'), ('feature', 'Yangi imkoniyat')], default='feedback', max_length=20, verbose_name='Turi')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Baho (1-5)')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name="Mavzu / Bo'lim")),
                ('message', models.TextField(verbose_name='Xabar / Izoh')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fikr va taklif',
                'verbose_name_plural': 'Fikr va takliflar',
                'ordering': ['-created_at'],
            },
        ),
    ]
