# Generated by Django 6.0.7 on 2026-08-05 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('mode', models.CharField(choices=[('practice', "O'rganish"), ('exam', 'Imtihon')], default='practice', max_length=10, verbose_name='Rejim')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqti')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqti')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='catalog.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='Umumiy ball')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('incorrect_count', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar soni")),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Davomiyligi (soniya)')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='testengine.testsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('selected_option', models.CharField(max_length=1, verbose_name='Tanlangan javob')),
                ('is_correct', models.BooleanField(verbose_name="To'g'ri/noto'g'ri")),
                ('confidence', models.CharField(blank=True, choices=[('sure', 'Ishonchli'), ('guess', 'Taxmin')], max_length=10, verbose_name='Ishonch darajasi')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='catalog.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testengine.testsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
