# Generated by Django 6.0.7 on 2026-08-22 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_duplicate_answers(apps, schema_editor):
    """`uniq_answer_per_session_question` qo'yishdan oldin eski dublikatlarni
    tozalaydi. Constraint yo'q paytda bitta savolga bir nechta javob yozilgan
    bo'lishi mumkin — eng oxirgisi (eng katta id) qoldiriladi."""
    Answer = apps.get_model('testengine', 'Answer')
    seen = set()
    duplicate_ids = []
    for pk, session_id, question_id in (
        Answer.objects.order_by('-id').values_list('id', 'session_id', 'question_id').iterator()
    ):
        key = (session_id, question_id)
        if key in seen:
            duplicate_ids.append(pk)
        else:
            seen.add(key)

    for start in range(0, len(duplicate_ids), 1000):
        Answer.objects.filter(id__in=duplicate_ids[start:start + 1000]).delete()


def backfill_session_questions(apps, schema_editor):
    """Eski sessiyalarda savollar ro'yxati qotirilmagan — javob berilgan
    savollardan tiklaymiz, aks holda `/questions/` endpointi ular uchun
    bo'sh qaytadi."""
    TestSession = apps.get_model('testengine', 'TestSession')
    SessionQuestion = apps.get_model('testengine', 'SessionQuestion')
    Answer = apps.get_model('testengine', 'Answer')

    rows = []
    counts = {}
    current_session = None
    order = 0

    answers = Answer.objects.order_by('session_id', 'id').values_list(
        'session_id', 'question_id'
    )
    for session_id, question_id in answers.iterator(chunk_size=2000):
        if session_id != current_session:
            current_session = session_id
            order = 0
        order += 1
        counts[session_id] = order
        rows.append(SessionQuestion(
            session_id=session_id, question_id=question_id, order=order
        ))

    if rows:
        SessionQuestion.objects.bulk_create(rows, batch_size=1000)

    # Eski sessiyalarda "nechta savol" degan tushuncha yo'q edi, shuning uchun
    # `question_count` uchun tiklangan ro'yxat uzunligi yagona to'g'ri qiymat.
    # Aks holda sessiya "15 ta savol" deb ko'rinib, ro'yxatda 3 tasi chiqadi.
    for session_id, total in counts.items():
        TestSession.objects.filter(pk=session_id).update(question_count=total)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('testengine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Sessiya savoli',
                'verbose_name_plural': 'Sessiya savollari',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='testresult',
            name='unanswered_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Javobsiz savollar soni'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Savollar soni'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['session'], name='testengine__session_e4c7de_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['user', '-created_at'], name='testengine__user_id_d8f377_idx'),
        ),
        migrations.RunPython(drop_duplicate_answers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='uniq_answer_per_session_question'),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='catalog.question'),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='testengine.testsession'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='uniq_session_question_order'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='uniq_session_question'),
        ),
        migrations.RunPython(backfill_session_questions, migrations.RunPython.noop),
    ]
