# Generated by Django 6.0.7 on 2026-09-07 13:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_grade_question_lifecycle'),
        ('testengine', '0002_sessionquestion_alter_answer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTopicUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana (UZT)')),
                ('sessions_started', models.PositiveSmallIntegerField(default=1, verbose_name='Ochilgan testlar')),
            ],
            options={
                'verbose_name': 'Kunlik mavzu hisobi',
                'verbose_name_plural': 'Kunlik mavzu hisoblari',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExplanationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana (UZT)')),
            ],
            options={
                'verbose_name': 'Izoh ochilishi',
                'verbose_name_plural': 'Izoh ochilishlari',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='testsession',
            name='auto_finished',
            field=models.BooleanField(default=False, verbose_name='Avtomatik yakunlangan'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash muddati'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sessions', to='catalog.grade', verbose_name='Sinf / Kitob'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vaqt chegarasi (soniya)'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sessions', to='catalog.topic', verbose_name='Mavzu'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(condition=models.Q(('finished_at__isnull', True)), fields=['expires_at'], name='idx_session_open_expiry'),
        ),
        migrations.AddField(
            model_name='dailytopicusage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to='catalog.topic'),
        ),
        migrations.AddField(
            model_name='dailytopicusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_topic_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='explanationusage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanation_usages', to='testengine.testsession'),
        ),
        migrations.AddField(
            model_name='explanationusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanation_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailytopicusage',
            index=models.Index(fields=['user', 'date'], name='testengine__user_id_1ffeca_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailytopicusage',
            constraint=models.UniqueConstraint(fields=('user', 'topic', 'date'), name='uniq_daily_topic_usage'),
        ),
        migrations.AddIndex(
            model_name='explanationusage',
            index=models.Index(fields=['user', 'date'], name='testengine__user_id_444b19_idx'),
        ),
        migrations.AddConstraint(
            model_name='explanationusage',
            constraint=models.UniqueConstraint(fields=('user', 'session', 'date'), name='uniq_explanation_usage'),
        ),
    ]
