# Generated by Django 6.0.7 on 2026-09-23 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_grade_question_lifecycle'),
        ('testengine', '0003_dailytopicusage_explanationusage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='exam_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Blok imtihonida fanlar shu tartibda chiqadi.', verbose_name='Imtihondagi tartibi'),
        ),
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('time_limit_seconds', models.PositiveIntegerField(verbose_name='Umumiy vaqt (soniya)')),
                ('expires_at', models.DateTimeField(verbose_name='Tugash muddati')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqti')),
                ('auto_finished', models.BooleanField(default=False, verbose_name='Avtomatik yakunlangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blok imtihoni',
                'verbose_name_plural': 'Blok imtihonlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testsession',
            name='mock_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='testengine.mockexam', verbose_name='Blok imtihoni'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['mock_exam', 'exam_order'], name='testengine__mock_ex_393e04_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['user', '-created_at'], name='testengine__user_id_88cf1d_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(condition=models.Q(('finished_at__isnull', True)), fields=['expires_at'], name='idx_mock_exam_open_expiry'),
        ),
    ]
