# Generated by Django 6.0.7 on 2026-08-11 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('testengine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('period', models.CharField(choices=[('daily', 'Bugungi kun'), ('weekly', 'Bu hafta'), ('all_time', 'Umumiy')], max_length=20, verbose_name='Reyting turi')),
                ('stars', models.FloatField(default=0.0, verbose_name='⭐ XP yulduzlari')),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='Tugagan testlar soni')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('incorrect_answers', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar soni")),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Reyting joylanishi')),
                ('period_start_date', models.DateField(verbose_name='Davr boshlanish sanasi')),
                ('period_end_date', models.DateField(verbose_name='Davr tugash sanasi')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-stars', '-tests_completed'],
            },
        ),
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('previous_stars', models.FloatField(blank=True, null=True, verbose_name='Oldingi ⭐')),
                ('new_stars', models.FloatField(verbose_name='Yangi ⭐')),
                ('stars_change', models.FloatField(verbose_name="O'zgarish miqdori")),
                ('previous_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Oldingi reyting joylanishi')),
                ('new_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yangi reyting joylanishi')),
                ('reason', models.CharField(max_length=255, verbose_name="O'zgarish sababi")),
                ('period', models.CharField(choices=[('daily', 'Bugungi kun'), ('weekly', 'Bu hafta'), ('all_time', 'Umumiy')], max_length=20, verbose_name='Qaysi davr yangilandi')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rating.rating')),
                ('test_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_changes', to='testengine.testsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('stars', models.FloatField(default=0.0, verbose_name='⭐ Fan reytingi')),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='Tugagan testlar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('incorrect_answers', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar")),
                ('topics_completed', models.PositiveIntegerField(default=0, verbose_name="O'tigan mavzular soni")),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqt')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalog.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-stars'],
            },
        ),
        migrations.CreateModel(
            name='TopicRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('stars', models.FloatField(default=0.0, verbose_name='⭐ Mavzu reytingi')),
                ('tests_completed', models.PositiveIntegerField(default=0, verbose_name='Tugagan testlar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('incorrect_answers', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar")),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqt')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalog.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-stars'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('period', models.CharField(choices=[('daily', 'Bugungi kun'), ('weekly', 'Bu hafta'), ('all_time', 'Umumiy')], max_length=20, verbose_name='Davr')),
                ('rank', models.PositiveIntegerField(verbose_name="O'rni")),
                ('stars', models.FloatField(verbose_name='⭐ Yulduzlar')),
                ('tests_completed', models.PositiveIntegerField(verbose_name='Tugagan testlar')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rank'],
                'indexes': [models.Index(fields=['period', 'date', 'rank'], name='rating_lead_period_22c9d9_idx'), models.Index(fields=['user', 'period'], name='rating_lead_user_id_12cb78_idx')],
                'unique_together': {('period', 'rank', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['period', '-stars'], name='rating_rati_period_6f91d3_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['period', 'period_start_date'], name='rating_rati_period_3a8b4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'period', 'period_start_date', 'period_end_date')},
        ),
        migrations.AddIndex(
            model_name='ratinghistory',
            index=models.Index(fields=['user', '-created_at'], name='rating_rati_user_id_4857f4_idx'),
        ),
        migrations.AddIndex(
            model_name='ratinghistory',
            index=models.Index(fields=['period', '-created_at'], name='rating_rati_period_cfc900_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectrating',
            index=models.Index(fields=['user', 'subject'], name='rating_subj_user_id_662a39_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectrating',
            index=models.Index(fields=['user', '-stars'], name='rating_subj_user_id_528298_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectrating',
            unique_together={('user', 'subject')},
        ),
        migrations.AddIndex(
            model_name='topicrating',
            index=models.Index(fields=['user', 'topic'], name='rating_topi_user_id_ec7b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='topicrating',
            index=models.Index(fields=['user', '-stars'], name='rating_topi_user_id_ab566b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicrating',
            unique_together={('user', 'topic')},
        ),
    ]
