# Generated by Django 6.0.7 on 2026-08-11 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('date', models.DateField(verbose_name='Sana')),
                ('timeframe', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], max_length=20, verbose_name='Davr')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Jami foydalanuvchilar')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='Faol foydalanuvchilar')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='Yangi foydalanuvchilar')),
                ('total_tests_completed', models.PositiveIntegerField(default=0, verbose_name='Jami tugagan testlar')),
                ('average_accuracy', models.FloatField(default=0.0, verbose_name="O'rtacha to'g'rilik %")),
                ('average_rating', models.FloatField(default=0.0, verbose_name="O'rtacha reyting ⭐")),
                ('active_subscriptions', models.PositiveIntegerField(default=0, verbose_name='Faol obunalar')),
                ('expired_subscriptions', models.PositiveIntegerField(default=0, verbose_name="Muddati o'tgan obunalar")),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Jami daromad')),
                ('engagement_rate', models.FloatField(default=0.0, verbose_name='Ishtirok darajasi %')),
                ('retention_rate', models.FloatField(default=0.0, verbose_name='Qaytishi darajasi %')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqt')),
                ('top_subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='catalog.subject')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='DashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('dashboard_type', models.CharField(choices=[('mentor', 'Mentor Dashboard'), ('admin', 'Admin Dashboard'), ('analytics', 'Analytics')], max_length=20, verbose_name='Dashboard turi')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Kirgan vaqti')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzili')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name="Qo'shilgan vaqt (minut)")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['user', 'dashboard_type'], name='dashboard_d_user_id_3209c9_idx'), models.Index(fields=['accessed_at'], name='dashboard_d_accesse_a0d401_idx')],
            },
        ),
        migrations.CreateModel(
            name='MentorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('alert_type', models.CharField(choices=[('low_performance', 'Past faollik'), ('no_activity', "Faollik yo'q"), ('low_rating', 'Past reyting'), ('streak_broken', 'Streak uzildi'), ('needs_review', "Ko'rikni keraki")], max_length=20, verbose_name='Ogohlantirish turi')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('resolved', 'Hal qilindi'), ('ignored', 'Rad etildi')], default='open', max_length=20, verbose_name='Holati')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqti')),
                ('action_taken', models.TextField(blank=True, verbose_name='Qabul qilingan haraka')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mentor', 'status'], name='dashboard_m_mentor__17e2fb_idx'), models.Index(fields=['student', '-created_at'], name='dashboard_m_student_6329d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MentorStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Tayinlangan vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentored_students', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('mentor', 'student')},
            },
        ),
    ]
