# Generated by Django 6.0.7 on 2026-08-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['topic_id', 'id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/%Y/%m/', verbose_name='Rasm (ixtiyoriy)'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rasm izohi'),
        ),
        migrations.AddField(
            model_name='question',
            name='options_en',
            field=models.JSONField(blank=True, null=True, verbose_name='Variantlar (EN)'),
        ),
        migrations.AddField(
            model_name='question',
            name='options_ru',
            field=models.JSONField(blank=True, null=True, verbose_name='Variantlar (RU)'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='Savol matni (EN)'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='Savol matni (RU)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (EN)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (RU)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nomi (EN)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(verbose_name='Variantlar (UZ)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Savol matni (UZ)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi (UZ)'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nomi (UZ)'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty'], name='catalog_que_topic_i_f406f4_idx'),
        ),
    ]
