# Generated by Django 6.0.7 on 2026-08-12 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('scheduled_at', models.DateTimeField(verbose_name='Joylash sanasi va vaqti')),
                ('status', models.CharField(choices=[('draft', 'Chizmasi'), ('scheduled', 'Rejalashtirilgan'), ('sent', 'Yuborildi'), ('failed', 'Yuborilmadi')], default='draft', max_length=20, verbose_name='Holati')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Yuborilgan soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name_plural': 'Umumiy xabarlar',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('notification_type', models.CharField(choices=[('rank_up', "Reyting ko'tarilishi"), ('rank_down', 'Reyting tushishi'), ('milestone', 'Taxt belgilari'), ('achievement', 'Yutuq')], max_length=20, verbose_name='Turi')),
                ('template', models.TextField(verbose_name='Xabar shabloni ({{variable}} formatida)')),
                ('old_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Oldingi reyting')),
                ('new_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yangi reyting')),
                ('rank_change', models.IntegerField(default=0, verbose_name="Reyting o'zgarish miqdori")),
                ('old_stars', models.FloatField(blank=True, null=True, verbose_name='Oldingi yulduzlar')),
                ('new_stars', models.FloatField(blank=True, null=True, verbose_name='Yangi yulduzlar')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Yuborilganmi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name_plural': 'Dinamik xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncompleteTestReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('course_name', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('total_topics', models.PositiveIntegerField(verbose_name='Jami mavzular soni')),
                ('completed_topics', models.PositiveIntegerField(verbose_name='Tugagan mavzular soni')),
                ('last_topic_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tugangan oxirgi mavzu')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Yuborilganmi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqti')),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi eslatma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name_plural': 'Tugallanmagan test eslatmalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('notification_type', models.CharField(choices=[('new_device_login', 'Yangi qurilmadan kirish'), ('new_location_login', 'Yangi joydan kirish'), ('account_created', 'Hisob yaratildi'), ('suspicious_login', 'Shubhali kirish')], max_length=30, verbose_name='Turi')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('device_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qurilma nomi')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qurilma turi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Joylashuvi')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilganmi")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqti")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name_plural': 'Xavfsizlik xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='content_type',
            field=models.CharField(default='broadcast', max_length=50, verbose_name='Xabar turi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Xatolik xabar'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='object_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Xabar ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('push', 'Push'), ('email', 'Email')], max_length=20, verbose_name='Kanal'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Yuborilmadi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_57d53d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'sent_at'], name='notificatio_status_0f5643_idx'),
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incompletetestreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomplete_test_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitynotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='incompletetestreminder',
            unique_together={('user', 'course_name')},
        ),
    ]
