# Generated by Django 6.0.7 on 2026-08-13 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_broadcastnotification_dynamicnotification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Yuborildimi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqti')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Nechta userga yetdi')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='broadcastnotification',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='dynamicnotification',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='incompletetestreminder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='incompletetestreminder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pushtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reminderschedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='securitynotification',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='notificationlog',
            name='notificatio_status_0f5643_idx',
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name="O'qilganmi"),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan vaqti"),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('welcome', "Ro'yxatdan o'tish tabrigi"), ('rating_up', "Reyting ko'tarilishi"), ('announcement', "Umumiy e'lon")], default=1, max_length=20, verbose_name='Turi'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_d9b354_idx'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BroadcastNotification',
        ),
        migrations.DeleteModel(
            name='DynamicNotification',
        ),
        migrations.DeleteModel(
            name='IncompleteTestReminder',
        ),
        migrations.DeleteModel(
            name='PushToken',
        ),
        migrations.DeleteModel(
            name='ReminderSchedule',
        ),
        migrations.DeleteModel(
            name='SecurityNotification',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='status',
        ),
    ]
