# Generated by Django 6.0.7 on 2026-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_announcement_remove_broadcastnotification_admin_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('welcome', "Ro'yxatdan o'tish tabrigi"), ('rating_up', "Reyting ko'tarilishi"), ('announcement', "Umumiy e'lon"), ('sub_approved', 'Obuna tasdiqlandi'), ('sub_rejected', 'Obuna arizasi rad etildi'), ('sub_expiring', 'Obuna muddati tugayapti'), ('test_finished', 'Test yakunlandi')], max_length=20, verbose_name='Turi'),
        ),
    ]
