# Generated by Django 6.0.7 on 2026-09-23 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntroQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('kind', models.CharField(choices=[('logic', 'Mantiqiy'), ('psychology', 'Psixologik')], default='logic', help_text="Psixologik savolda to'g'ri javob bo'lmaydi.", max_length=12, verbose_name='Turi')),
                ('text', models.TextField(verbose_name='Savol matni (UZ)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Savol matni (RU)')),
                ('text_en', models.TextField(blank=True, verbose_name='Savol matni (EN)')),
                ('options', models.JSONField(help_text='Masalan: {"A": "Birinchi", "B": "Ikkinchi", "C": "Uchinchi"}', verbose_name='Variantlar (UZ)')),
                ('options_ru', models.JSONField(blank=True, null=True, verbose_name='Variantlar (RU)')),
                ('options_en', models.JSONField(blank=True, null=True, verbose_name='Variantlar (EN)')),
                ('correct_option', models.CharField(blank=True, help_text="Mantiqiy savol uchun majburiy, psixologik uchun bo'sh qoldiriladi.", max_length=1, verbose_name="To'g'ri javob")),
                ('image', models.ImageField(blank=True, null=True, upload_to='intro/images/%Y/%m/', verbose_name='Rasm (ixtiyoriy)')),
                ('video', models.FileField(blank=True, help_text="50 MB gacha. Doimiy saqlash uchun tashqi xotira kerak — server diski redeploy'da tozalanadi.", null=True, upload_to='intro/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'm4v'])], verbose_name='Video (ixtiyoriy)')),
                ('video_url', models.URLField(blank=True, help_text="YouTube yoki boshqa havola. Fayl yuklashdan ko'ra yengilroq.", verbose_name='Video havolasi (ixtiyoriy)')),
                ('explanation', models.TextField(blank=True, help_text="Test yakunida ko'rsatiladi.", verbose_name='Javobdan keyingi izoh (UZ)')),
                ('explanation_ru', models.TextField(blank=True, verbose_name='Javobdan keyingi izoh (RU)')),
                ('explanation_en', models.TextField(blank=True, verbose_name='Javobdan keyingi izoh (EN)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kirish testi savoli',
                'verbose_name_plural': 'Kirish testi savollari',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'kind'], name='intro_intro_is_acti_0a00cd_idx')],
            },
        ),
    ]
